# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.synced_folder "../", "/opt/floridsword"
  config.vm.provision "shell", path: "../setup/install.sh", args: "--skip-puppet"
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose --debug"
    puppet.environment_path = "../setup/environments"
    puppet.environment = "production"
  end

  config.vm.define "fw", primary: true do |fw|
    fw.vm.hostname = "fw.anniera.isle"
    fw.vm.box = "ubuntu/xenial64"
    fw.vm.network "private_network", ip: "10.123.234.254", virtualbox__intnet: true
    fw.vm.network "forwarded_port", guest: 5000, host: 5000, auto_correct: true
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client.anniera.isle"
    client.vm.box = "ubuntu/xenial64"
    client.vm.network "private_network", type: "dhcp", virtualbox__intnet: true
    client.vm.provider "virtualbox" do |v|
      v.gui = true
      v.memory = 1024
    end
  end
end
